FROM public.ecr.aws/lambda/python:3.9

RUN yum install -y \
  autoconf \
  automake \
  cmake \
  gcc \
  gcc-c++ \
  libtool \
  make \
  nasm \
  pkgconfig

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy function code
COPY modelfile.gguf /opt/modelfile.gguf

# Install the function's dependencies using file requirements.txt
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# COPY all code source
COPY *.py .

CMD [ "main.handler" ]
